spring:
  datasource:
    url: jdbc:mysql://localhost/my_library
    username: root
    password: root

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  hibernate:
    ddl-auto: create-drop

server:
  error:
    include-stacktrace: always

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
# Caso seja necessário mudar os parâmetros que serão usados pelo FrontEnd, cabe aqui modificar o nome que será usado pelo cliente HTTP
# data:
#   web:
#     pageable:
#       page-parameter: pagina
#       size-parameter: tamanho
#     sort:
#       sort-parameter: ordem