CREATE TABLE livro (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    ano_publicacao INT NOT NULL,
    editora VARCHAR(100) NOT NULL,
    genero VARCHAR(100) NOT NULL,
    isbn VARCHAR(100) NOT NULL
);